# Find author qids using wikidata's GBDE (German Projekt Gutenberg) author IDs

Such IDs are derived from the URL and take the for of a short string derived from the authors last name, see below for some examples. The value is attached to an author entity using the ID property wdt:P7753

In [39]:
import logging
logging.basicConfig(filename='Find_Author_Qid_using_PGDE_id.log', 
                    format='%(asctime)s %(message)s', 
                    datefmt='%Y/%m/%d %H:%M:%S',
                    encoding='utf-8', 
                    level=logging.DEBUG)

logger = logging.getLogger('')
logger.debug('Start logging')

In [1]:
from pathlib import Path
import pandas as pd
from datetime import datetime
from wikibaseintegrator.wbi_config import config as wbi_config
from wikibaseintegrator import WikibaseIntegrator, wbi_helpers, wbi_login, datatypes
import json
import re

USERNAME = 'LiteraryWorksMetaDataUploadBot'

wbi_config['USER_AGENT'] = f'{USERNAME} [1.0] (https://www.wikidata.org/wiki/User:{USERNAME})'
wbi_config['MEDIAWIKI_API_URL'] = 'https://www.wikidata.org/w/api.php'

In [41]:
collections_dir = Path("../metadata_collections/")
pg_dir = Path("../data_PG/")

def date_tag():
    return datetime.today().strftime("%Y-%m-%dT%H:%M")

def qid_from_url(url : str):
    return re.search(r'Q\d+$',url).group()

### Load our metadata file

The pgde_author_id contains what wikidata calls GBDE author id. We extracted this value from the URL when we scraped the texts.

In [42]:
#filename = 'de-fiction-wd-url2025-11-13T19:10:33.csv'
filename = 'de_fiction_metadata_2025-11-14T17.csv'
logger.info(f'Opening file: {filename}')
fiction = pd.read_csv(Path(collections_dir, filename), index_col=0, dtype={'gutenberg_id':str})
fiction

,author,author_last,author_first,title,work_qid,gutenberg_id,year,url,pgde_author_id,author_qid,...,filename,author_gender,num_sents,num_tokens,source,work_qid_by,pgde_qid_by,pgus_qid_by,ed1_qid_by,1e_qid_by
index,,,,,,,,,,,,,,,,,,,,,
0,Arthur Achleitner,Achleitner,Arthur,Der Finanzer,NaN,NaN,1916,https://www.projekt-gutenberg.org/achleitn/fin...,achleitn,Q77439,...,Arthur_Achleitner_-_Der_Finanzer.txt,m,1723,24034,PG-DE,NaN,NaN,NaN,NaN,NaN
1,Arthur Achleitner,Achleitner,Arthur,Das Schloß im Moor,NaN,NaN,1903,https://www.projekt-gutenberg.org/achleitn/moo...,achleitn,Q77439,...,Arthur_Achleitner_-_Das_Schloß_im_Moor.txt,m,3460,51072,PG-DE,NaN,NaN,NaN,NaN,NaN
2,Arthur Achleitner,Achleitner,Arthur,Familie Lugmüller,NaN,NaN,1896,https://www.projekt-gutenberg.org/achleitn/lug...,achleitn,Q77439,...,Arthur_Achleitner_-_Familie_Lugmüller.txt,m,1967,26741,PG-DE,NaN,NaN,NaN,NaN,NaN
3,Arthur Achleitner,Achleitner,Arthur,Der Bezirkshauptmann. Erster Teil,NaN,NaN,1901,https://www.projekt-gutenberg.org/achleitn/bez...,achleitn,Q77439,...,Arthur_Achleitner_-_Der_Bezirkshauptmann._Erst...,m,2614,34895,PG-DE,NaN,NaN,NaN,NaN,NaN
4,Arthur Achleitner,Achleitner,Arthur,Geschichten aus den Bergen,NaN,NaN,1910,https://www.projekt-gutenberg.org/achleitn/ber...,achleitn,Q77439,...,Arthur_Achleitner_-_Geschichten_aus_den_Bergen...,m,6350,127192,PG-DE,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4229,Arnold Zweig,Zweig,Arnold,Die Novellen um Claudia,NaN,52478,1912,NaN,NaN,NaN,...,"Zweig,_Arnold_-_Die_Novellen_um_Claudia-52478.txt",m,2720,47335,PG-US,NaN,NaN,NaN,NaN,NaN
4230,Friderike Maria Burger Winternitz Zweig,Zweig,Friderike Maria Burger Winternitz,Vögelchen,NaN,57114,1919,NaN,NaN,NaN,...,"Zweig,_Friderike_Maria_Burger_Winternitz_-_Vög...",m,7846,104521,PG-US,NaN,NaN,NaN,NaN,NaN
4231,Stefan Zweig,Zweig,Stefan,Amok: Novellen einer Leidenschaft,Q675609,57850,1922,NaN,zweig,Q78491,...,"Zweig,_Stefan_-_Amok:_Novellen_einer_Leidensch...",m,3087,69716,PG-US,NaN,NaN,NaN,NaN,NaN
4232,Stefan Zweig,Zweig,Stefan,Brennendes Geheimnis: Erzählung,NaN,24173,1911,NaN,NaN,Q78491,...,"Zweig,_Stefan_-_Brennendes_Geheimnis:_Erzählun...",m,1475,22509,PG-US,NaN,NaN,NaN,NaN,NaN
4233,Stefan Zweig,Zweig,Stefan,Die Liebe der Erika Ewald: Novellen,NaN,38686,1904,NaN,NaN,Q78491,...,"Zweig,_Stefan_-_Die_Liebe_der_Erika_Ewald:_Nov...",m,2391,44067,PG-US,NaN,NaN,NaN,NaN,NaN

### Query Wikidata for all GBDE author IDs

Could do this somewhat more carefully and only ask for one title, or only for German works

In [43]:
query = """SELECT ?author_qid ?author_qidLabel ?gbde_author_id 
        WHERE
        {
        ?author_qid wdt:P7753 ?gbde_author_id .
        SERVICE wikibase:label { bd:serviceParam wikibase:language "de,mul,en". }
        }
        ORDER BY desc(?author_qidLabel) desc(?title)"""

result = wbi_helpers.execute_sparql_query(query, 
                                            user_agent=wbi_config['USER_AGENT'])
result

{'head': {'vars': ['author_qid', 'author_qidLabel', 'gbde_author_id']},
 'results': {'bindings': [{'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q692'},
    'gbde_author_id': {'type': 'literal', 'value': 'shakespr'},
    'author_qidLabel': {'xml:lang': 'mul',
     'type': 'literal',
     'value': 'William Shakespeare'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q2172949'},
    'gbde_author_id': {'type': 'literal', 'value': 'herzog'},
    'author_qidLabel': {'xml:lang': 'mul',
     'type': 'literal',
     'value': 'Rudolf Herzog'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q7245'},
    'gbde_author_id': {'type': 'literal', 'value': 'twain'},
    'author_qidLabel': {'xml:lang': 'mul',
     'type': 'literal',
     'value': 'Mark Twain'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q590'},
    'gbde_author_id': {'type': 'literal', 'value': 'camoes'},
    'author_qidLabel': {'xml:lang': 'mul',
     'type': 'literal',
     'value': 'Luís de Camões'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q191305'},
    'gbde_author_id': {'type': 'literal', 'value': 'nerval'},
    'author_qidLabel': {'xml:lang': 'mul',
     'type': 'literal',
     'value': 'Gérard de Nerval'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q3816'},
    'gbde_author_id': {'type': 'literal', 'value': 'sand'},
    'author_qidLabel': {'xml:lang': 'mul',
     'type': 'literal',
     'value': 'George Sand'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q1067'},
    'gbde_author_id': {'type': 'literal', 'value': 'dante'},
    'author_qidLabel': {'xml:lang': 'mul',
     'type': 'literal',
     'value': 'Dante Alighieri'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q1035'},
    'gbde_author_id': {'type': 'literal', 'value': 'darwin'},
    'author_qidLabel': {'xml:lang': 'mul',
     'type': 'literal',
     'value': 'Charles Darwin'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q1242600'},
    'gbde_author_id': {'type': 'literal', 'value': 'pasztor'},
    'author_qidLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Árpád Pásztor'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q20731648'},
    'gbde_author_id': {'type': 'literal', 'value': 'lescomba'},
    'author_qidLabel': {'xml:lang': 'en',
     'type': 'literal',
     'value': 'Marie Catherine Taperet'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q84455'},
    'gbde_author_id': {'type': 'literal', 'value': 'horvath'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Ödön von Horváth'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q290227'},
    'gbde_author_id': {'type': 'literal', 'value': 'boetie'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Étienne de La Boétie'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q504'},
    'gbde_author_id': {'type': 'literal', 'value': 'zola'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Émile Zola'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q193680'},
    'gbde_author_id': {'type': 'literal', 'value': 'verhaere'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Émile Verhaeren'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q463513'},
    'gbde_author_id': {'type': 'literal', 'value': 'gaboriau'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Émile Gaboriau'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q3246593'},
    'gbde_author_id': {'type': 'literal', 'value': 'erckmann'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Émile Erckmann'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q122356'},
    'gbde_author_id': {'type': 'literal', 'value': 'rod'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Édouard Rod'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q18115592'},
    'gbde_author_id': {'type': 'literal', 'value': 'maynial'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Édouard Maynial'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q43423'},
    'gbde_author_id': {'type': 'literal', 'value': 'aesop'},
    'author_qidLabel': {'xml:lang': 'de', 'type': 'literal', 'value': 'Äsop'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q191377'},
    'gbde_author_id': {'type': 'literal', 'value': 'zettl'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Zephyrin Zettl'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q12344242'},
    'gbde_author_id': {'type': 'literal', 'value': 'nielsen'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Zakarias Nielsen'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q129772'},
    'gbde_author_id': {'type': 'literal', 'value': 'xenophon'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Xenophon'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q121180'},
    'gbde_author_id': {'type': 'literal', 'value': 'reymont'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Władysław Reymont'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q333222'},
    'gbde_author_id': {'type': 'literal', 'value': 'garschin'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wsewolod Michailowitsch Garschin'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q18821'},
    'gbde_author_id': {'type': 'literal', 'value': 'eschenba'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wolfram von Eschenbach'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q87838'},
    'gbde_author_id': {'type': 'literal', 'value': 'kirchbac'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wolfgang Kirchbach'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q23710233'},
    'gbde_author_id': {'type': 'literal', 'value': 'hellmert'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wolfgang Hellmert'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q58799'},
    'gbde_author_id': {'type': 'literal', 'value': 'borchert'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wolfgang Borchert'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q254'},
    'gbde_author_id': {'type': 'literal', 'value': 'mozart'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wolfgang Amadeus Mozart'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q2588858'},
    'gbde_author_id': {'type': 'literal', 'value': 'kalckreu'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wolf von Kalckreuth'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q215699'},
    'gbde_author_id': {'type': 'literal', 'value': 'baudissi'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wolf Heinrich von Baudissin'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q98142'},
    'gbde_author_id': {'type': 'literal', 'value': 'baudiswg'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wolf Ernst Hugo Emil von Baudissin'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q55896154'},
    'gbde_author_id': {'type': 'literal', 'value': 'uxkull'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Woldemar Uexküll-Gyllenband'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q19844040'},
    'gbde_author_id': {'type': 'literal', 'value': 'solitair'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Woldemar Nürnberger'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q335064'},
    'gbde_author_id': {'type': 'literal', 'value': 'korolenk'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wladimir Galaktionowitsch Korolenko'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q111110'},
    'gbde_author_id': {'type': 'literal', 'value': 'seidelw'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Willy Seidel'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q1397844'},
    'gbde_author_id': {'type': 'literal', 'value': 'pastor'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Willy Pastor'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q84411289'},
    'gbde_author_id': {'type': 'literal', 'value': 'rudinoff'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Willibald Wolf Rudinoff'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q77312'},
    'gbde_author_id': {'type': 'literal', 'value': 'alexis'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Willibald Alexis'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q167768'},
    'gbde_author_id': {'type': 'literal', 'value': 'thackera'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'William Makepeace Thackeray'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q1232165'},
    'gbde_author_id': {'type': 'literal', 'value': 'lequeux'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'William Le Queux'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q3568747'},
    'gbde_author_id': {'type': 'literal', 'value': 'lockewj'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'William John Locke'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q12407121'},
    'gbde_author_id': {'type': 'literal', 'value': 'russel'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'William Clark Russell'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q40213'},
    'gbde_author_id': {'type': 'literal', 'value': 'yeats'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'William Butler Yeats'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q19975164'},
    'gbde_author_id': {'type': 'literal', 'value': 'bolitho'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'William Bolitho Ryall'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q361026'},
    'gbde_author_id': {'type': 'literal', 'value': 'beckford'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'William Beckford'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q1414628'},
    'gbde_author_id': {'type': 'literal', 'value': 'handl'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Willi Handl'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q210740'},
    'gbde_author_id': {'type': 'literal', 'value': 'collins'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilkie Collins'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q237740'},
    'gbde_author_id': {'type': 'literal', 'value': 'wvbayreu'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelmine von Preußen'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q88281'},
    'gbde_author_id': {'type': 'literal', 'value': 'hillern'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelmine von Hillern'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q75922'},
    'gbde_author_id': {'type': 'literal', 'value': 'heimburg'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelmine Heimburg'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q1555222'},
    'gbde_author_id': {'type': 'literal', 'value': 'polenz'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm von Polenz'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q288186'},
    'gbde_author_id': {'type': 'literal', 'value': 'kuegelgn'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm von Kügelgen'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q77888'},
    'gbde_author_id': {'type': 'literal', 'value': 'humboldw'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm von Humboldt'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q64607'},
    'gbde_author_id': {'type': 'literal', 'value': 'bode'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm von Bode'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q88478'},
    'gbde_author_id': {'type': 'literal', 'value': 'zimmerma'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm Zimmermann'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q75814'},
    'gbde_author_id': {'type': 'literal', 'value': 'wundt'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm Wundt'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q84412539'},
    'gbde_author_id': {'type': 'literal', 'value': 'wiesebac'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm Wiesebach'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q91858'},
    'gbde_author_id': {'type': 'literal', 'value': 'walloth'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm Walloth'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q66015'},
    'gbde_author_id': {'type': 'literal', 'value': 'waibling'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm Waiblinger'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q62071'},
    'gbde_author_id': {'type': 'literal', 'value': 'voigtw'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm Voigt'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q76650'},
    'gbde_author_id': {'type': 'literal', 'value': 'schaefer'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm Schäfer'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q112136'},
    'gbde_author_id': {'type': 'literal', 'value': 'scherer'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm Scherer'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q2574741'},
    'gbde_author_id': {'type': 'literal', 'value': 'ruland'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm Ruland'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q60647'},
    'gbde_author_id': {'type': 'literal', 'value': 'raabe'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm Raabe'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q13189015'},
    'gbde_author_id': {'type': 'literal', 'value': 'poeck'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm Poeck'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q12658'},
    'gbde_author_id': {'type': 'literal', 'value': 'ostwald'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm Ostwald'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q57879'},
    'gbde_author_id': {'type': 'literal', 'value': 'muellerw'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm Müller'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q2574255'},
    'gbde_author_id': {'type': 'literal', 'value': 'bronnerb'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm Molitor'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q98376'},
    'gbde_author_id': {'type': 'literal', 'value': 'meyerfoe'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm Meyer-Förster'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q97304'},
    'gbde_author_id': {'type': 'literal', 'value': 'meinhold'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm Meinhold'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q19238757'},
    'gbde_author_id': {'type': 'literal', 'value': 'herbert'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm Mayer'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q2574017'},
    'gbde_author_id': {'type': 'literal', 'value': 'wekhrlin'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm Ludwig Wekhrlin'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q1565833'},
    'gbde_author_id': {'type': 'literal', 'value': 'langewie'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm Langewiesche'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q84760396'},
    'gbde_author_id': {'type': 'literal', 'value': 'kranzler'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm Kranzler'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q85072'},
    'gbde_author_id': {'type': 'literal', 'value': 'wasielew'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm Joseph von Wasielewski'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q71754'},
    'gbde_author_id': {'type': 'literal', 'value': 'jordan'},
    'author_qidLabel': {'xml:lang': 'de',
     'type': 'literal',
     'value': 'Wilhelm Jordan'}},
   {'author_qid': {'type': 'uri',
     'value': 'http://www.wikidata.org/entity/Q77444'},

### Make a GBDE author ID to QID dict

In [44]:
author_dict = { stmt['gbde_author_id']['value'] : qid_from_url(stmt['author_qid']['value']) for stmt in result['results']['bindings'] }
author_dict

{'shakespr': 'Q692',
 'herzog': 'Q2172949',
 'twain': 'Q7245',
 'camoes': 'Q590',
 'nerval': 'Q191305',
 'sand': 'Q3816',
 'dante': 'Q1067',
 'darwin': 'Q1035',
 'pasztor': 'Q1242600',
 'lescomba': 'Q20731648',
 'horvath': 'Q84455',
 'boetie': 'Q290227',
 'zola': 'Q504',
 'verhaere': 'Q193680',
 'gaboriau': 'Q463513',
 'erckmann': 'Q1348668',
 'rod': 'Q122356',
 'maynial': 'Q18115592',
 'aesop': 'Q43423',
 'zettl': 'Q191377',
 'nielsen': 'Q12344242',
 'xenophon': 'Q129772',
 'reymont': 'Q121180',
 'garschin': 'Q333222',
 'eschenba': 'Q18821',
 'kirchbac': 'Q87838',
 'hellmert': 'Q23710233',
 'borchert': 'Q58799',
 'mozart': 'Q254',
 'kalckreu': 'Q2588858',
 'baudissi': 'Q215699',
 'baudiswg': 'Q98142',
 'uxkull': 'Q55896154',
 'solitair': 'Q19844040',
 'korolenk': 'Q335064',
 'seidelw': 'Q111110',
 'pastor': 'Q1397844',
 'rudinoff': 'Q84411289',
 'alexis': 'Q77312',
 'thackera': 'Q167768',
 'lequeux': 'Q1232165',
 'lockewj': 'Q3568747',
 'russel': 'Q12407121',
 'yeats': 'Q40213',
 'bolitho': 'Q19975164',
 'beckford': 'Q361026',
 'handl': 'Q1414628',
 'collins': 'Q210740',
 'wvbayreu': 'Q237740',
 'hillern': 'Q88281',
 'heimburg': 'Q75922',
 'polenz': 'Q1555222',
 'kuegelgn': 'Q288186',
 'humboldw': 'Q77888',
 'bode': 'Q64607',
 'zimmerma': 'Q88478',
 'wundt': 'Q75814',
 'wiesebac': 'Q84412539',
 'walloth': 'Q91858',
 'waibling': 'Q66015',
 'voigtw': 'Q62071',
 'schaefer': 'Q76650',
 'scherer': 'Q112136',
 'ruland': 'Q2574741',
 'raabe': 'Q60647',
 'poeck': 'Q13189015',
 'ostwald': 'Q12658',
 'muellerw': 'Q57879',
 'bronnerb': 'Q2574255',
 'meyerfoe': 'Q98376',
 'meinhold': 'Q97304',
 'herbert': 'Q19238757',
 'wekhrlin': 'Q2574017',
 'langewie': 'Q1565833',
 'kranzler': 'Q84760396',
 'wasielew': 'Q85072',
 'jordan': 'Q71754',
 'jensen': 'Q77444',
 'holzamer': 'Q104139',
 'hey': 'Q106910',
 'hertz': 'Q91161',
 'heinse': 'Q64489',
 'wackenro': 'Q60576',
 'riehl': 'Q77020',
 'hegeler': 'Q110643',
 'hauff': 'Q57966',
 'soldan': 'Q2572850',
 'fischerw': 'Q2572659',
 'fischeww': 'Q41784052',
 'cremer': 'Q2572294',
 'corneliu': 'Q15455968',
 'boelsche': 'Q69727',
 'busch': 'Q109540',
 'blumenha': 'Q1424920',
 'asmus': 'Q2571751',
 'wvhohenb': 'Q2563044',
 'figner': 'Q266783',
 'weissros': 'Q153364',
 'andrewas': 'Q17392683',
 'irving': 'Q181667',
 'sacherwa': 'Q113750',
 'waltherv': 'Q44385',
 'siegfrd': 'Q80791654',
 'rathenau': 'Q135645',
 'nithack': 'Q19236831',
 'kabel': 'Q2547259',
 'harich': 'Q126931',
 'serner': 'Q646146',
 'seidlw': 'Q10839453',
 'scott': 'Q79025',
 'landor': 'Q645138',
 'rheiner': 'Q2545938',
 'horst': 'Q84418731',
 'hasencle': 'Q62628',
 'flex': 'Q73525',
 'bloem': 'Q109493',
 'benjamin': 'Q61078',
 'whitman': 'Q81438',
 'brjussow': 'Q316374',
 'voltaire': 'Q9068',
 'lachmanv': 'Q2531495',
 'woolf': 'Q40909',
 'van-gogh': 'Q5582',
 'knobelsd': 'Q81304818',
 'helling': 'Q84414277',
 'meric': 'Q3557470',
 'marguerv': 'Q2616465',
 'hugo': 'Q535',
 'hehn': 'Q89393',
 'hadwiger': 'Q1531588',
 'bluethge': 'Q98925',
 'auburtin': 'Q2522195',
 'baum': 'Q93444',
 'blascoib': 'Q219646',
 'heidenst': 'Q129173',
 'vergil': 'Q1398',
 'williams': 'Q3553609',
 'ulrichls': 'Q695576',
 'hutten': 'Q77107',
 'hegner': 'Q2475938',
 'braeker': 'Q121584',
 'uweson': 'Q84412624',
 'tartarug': 'Q1671138',
 'johansen': 'Q17119740',
 'bernhatr': 'Q379949',
 'tasso': 'Q168962',
 'schumact': 'Q94544',
 'masaryk': 'Q78492',
 'smollett': 'Q356283',
 'petroniu': 'Q47180',
 'livius': 'Q2039',
 'molina': 'Q295598',
 'kroeger': 'Q1576835',
 'gautier': 'Q183713',
 'thomasvk': 'Q220976',
 'wolfet': 'Q314256',
 'heineth': 'Q216004',
 'krag': 'Q934901',
 'morus': 'Q42544',
 'mooret': 'Q315346',
 'mannth': 'Q37030',
 'quincey': 'Q317160',
 'cobb': 'Q19630371',
 'carlyle': 'Q151403',
 'theresba': 'Q68918',
 'rie': 'Q2419609',
 'hubert': 'Q86167',
 'bentzon': 'Q4979605',
 'zolling': 'Q2419088',
 'kobbe': 'Q108022',
 'wundtt': 'Q2418500',
 'wolfft': 'Q120947',
 'volbehr': 'Q23925946',
 'storm': 'Q26993',
 'muegge': 'Q96453',
 'mundt': 'Q74688',
 'mommsen': 'Q25351',
 'meyermer': 'Q55123108',
 'lessingt': 'Q61446',
 'koerner': 'Q62344',
 'kirchhof': 'Q1648602',
 'herzl': 'Q44003',
 'panteniu': 'Q825743',
 'hippel': 'Q214310',
 'fontane': 'Q76632',
 'daeubler': 'Q1937725',
 'birt': 'Q109496',
 'berthold': 'Q2417349',
 'schneidt': 'Q1297703',
 'tacitus': 'Q2161',
 'lawrence': 'Q170596',
 'kierkega': 'Q6512',
 'lange': 'Q5934715',
 'elvestad': 'Q3498167',
 'normand': 'Q56635310',
 'gontard': 'Q97764',
 'sueton': 'Q10133',
 'mallarme': 'Q767',
 'stefbelg': 'Q170197',
 'milow': 'Q114786',
 'stendhal': 'Q502',
 'zweig': 'Q78491',
 'grossman': 'Q2336439',
 'george': 'Q57187',
 'blicher': 'Q347953',
 'przybysz': 'Q921405',
 'alcofora': 'Q268325',
 'bauditz': 'Q5567266',
 'sophokle': 'Q7235',
 'laroche': 'Q62404',
 'woerisho': 'Q75259',
 'brentans': 'Q66313',
 'hoechst': 'Q2302799',
 'haemmerl': 'Q2302792',
 'albrechs': 'Q1330321',
 'sokrates': 'Q913',
 'kowalews': 'Q184535',
 'hippius': 'Q61940',
 'linguet': 'Q1505526',
 'gfeller': 'Q1426560',
 'dach': 'Q77285',
 'pellico': 'Q435151',
 'gesell': 'Q22755',
 'freud': 'Q9215',
 'placzek': 'Q18207301',
 'bergengr': 'Q15445770',
 'zaeunema': 'Q92545',
 'gyp': 'Q199228',
 'frontinu': 'Q297377',
 'lieblein': 'Q4993059',
 'lagerloe': 'Q44519',
 'sailer': 'Q69534',
 'brant': 'Q60351',
 'aleichem': 'Q238090',
 'ascher': 'Q1437915',
 'smiles': 'Q1195422',
 'gardenhi': 'Q78759873',
 'hahneman': 'Q157056',
 'farina': 'Q1143985',
 'mosenthl': 'Q2214998',
 'gessner': 'Q123765',
 'dine': 'Q630454',
 'blaumani': 'Q1082044',
 'tanefiko': 'Q541039',
 'kipling': 'Q34743',
 'stratz': 'Q2174486',
 'genee': 'Q92053',
 'rudolfvh': 'Q152923',
 'tavel': 'Q124667',
 'ruets': 'Q84756208',
 'lossow': 'Q81498955',
 'kapri': 'Q27971166',
 'jhering': 'Q62605',
 'gottscha': 'Q96796',
 'stuerzer': 'Q15451398',
 'steiner': 'Q78484',
 'reusch': 'Q15549963',
 'reichena': 'Q16856414',
 'presber': 'Q1593671',
 'lindaur': 'Q85309',
 'koepke': 'Q78369',
 'kubitsch': 'Q54845985',
 'huchrud': 'Q96874',
 'hawel': 'Q115040',
 'greinz': 'Q90209',
 'binding': 'Q96026',
 'eucken': 'Q47695',
 'cronau': 'Q1644763',
 'braune': 'Q1772364',
 'baumbach': 'Q65888',
 'mayreder': 'Q89520',
 'luxembur': 'Q7231',
 'rollandr': 'Q47162',
 'betsch': 'Q2162667',
 'ottoleng': 'Q7357461',
 'toepffer': 'Q4247',
 'byr': 'Q1258506',
 'buchanan': 'Q5589250',
 'weilr': 'Q90342',
 'southey': 'Q216838',
 'seitz': 'Q1533968',
 'schweich': 'Q110165',
 'schumanr': 'Q7351',
 'reitzel': 'Q2158585',
 'muellerr': 'Q2158315',
 'musil': 'Q78487',
 'stevenso': 'Q1512',
 'kraftr': 'Q104254',
 'kohlraus': 'Q1554783',
 'heymann': 'Q1390219',
 'hamerlin': 'Q79088',
 'giseke': 'Q1598217',
 'fuchs-li': 'Q2157179',
 'scottf': 'Q102527',
 'peary': 'Q186585',
 'prutz': 'Q86152',
 'ascherrm': 'Q55676113',
 'volkmann': 'Q64707',
 'schaukal': 'Q86947',
 'kralik': 'Q1317482',
 'kraffteb': 'Q77082',
 'zoozmann': 'Q2150985',
 'wilhelm': 'Q62126',
 'wagner': 'Q1511',
 'vossr': 'Q71427',
 'skowronr': 'Q99760',
 'siegemun': 'Q84412455',
 'nordhaus': 'Q2150282',
 'muther': 'Q106176',
 'kuehnelt': 'Q2150017',
 'davis': 'Q922457',
 'dehmel': 'Q76590',
 'beer-hof': 'Q213750',
 'freeman': 'Q2065950',
 'bermann': 'Q1326745',
 'huchric': 'Q60785',
 'schickel': 'Q69322',
 'descarte': 'Q9191',
 'franken': 'Q81287140',
 'goeje': 'Q15881199',
 'ortmann': 'Q19225240',
 'eichacke': 'Q2141365',
 'sorge': 'Q69201',
 'goering': 'Q77886',
 'auernhei': 'Q85479',
 'emerson': 'Q48226',
 'rilke': 'Q76483',
 'varnhagr': 'Q61793',
 'sanzara': 'Q108097',
 'tagore': 'Q7241',
 'merimee': 'Q160333',
 'properz': 'Q8827',
 'mulford': 'Q1689726',
 'poggio': 'Q318254',
 'plautus': 'Q47160',
 'platon': 'Q859',
 'kropotki': 'Q5752',
 'aretino': 'Q296272',
 'beaumarc': 'Q70326',
 'laclos': 'Q212476',
 'brantome': 'Q733270',
 'valmiger': 'Q84426987',
 'louys': 'Q334958',
 'loti': 'Q311854',
 'corneill': 'Q747',
 'eulenbur': 'Q213964',
 'zesen': 'Q76458',
 'spiess': 'Q81528076',
 'scheidema': 'Q70581',
 'nicolaip': 'Q706203',
 'melancht': 'Q76325',
 'galen': 'Q214093',
 'rosegger': 'Q93841',
 'prosch': 'Q2077624',
 'nansenp': 'Q4349086',
 'hille': 'Q95693',
 'geibelp': 'Q1554313',
 'asbjoern': 'Q355485',
 'altenbrg': 'Q44972',
 'shelleyp': 'Q93343',
 'atterbom': 'Q444538',
 'calderon': 'Q170800',
 'alarcon': 'Q313553',
 'weisepau': 'Q84415706',
 'modersoh': 'Q234370',
 'dehmelp': 'Q114401',
 'lagarde': 'Q61310',
 'kock': 'Q982058',
 'zifferer': 'Q3372442',
 'zech': 'Q43166',
 'wertheim': 'Q49017329',
 'vernep': 'Q1785509',
 'verlaine': 'Q755',
 'steinmue': 'Q84412474',
 'ssymank': 'Q1416750',
 'schrecke': 'Q2062308',
 'sling': 'Q2062230',
 'scheerba': 'Q62435',
 'scarron': 'Q551725',
 'rosenhay': 'Q122228',
 'rebhun': 'Q2061804',
 'neubauer': 'Q20435070',
 'natorp': 'Q76504',
 'messnerp': 'Q81301035',
 'marguerp': 'Q2988469',
 'margot': 'Q84760391',
 'lindaup': 'Q86886',
 'levin': 'Q84417674',
 'leppin': 'Q85590',
 'langens': 'Q1649985',
 'lafargue': 'Q317152',
 'kruegerp': 'Q244407',
 'kornfeld': 'Q102799',
 'klee': 'Q44007',
 'kellerp': 'Q88204',
 'moebius': 'Q62402',
 'feuerbac': 'Q61929',
 'heyse': 'Q76487',
 'hansmann': 'Q55674497',
 'hambruch': 'Q105652',
 'hallerp': 'Q1727263',
 'grabein': 'Q2059843',
 'gerhardt': 'Q76331',
 'fleming': 'Q77418',
 'ernstp': 'Q72557',
 'enderlin': 'Q2059436',
 'busson': 'Q1504963',
 'bourget': 'Q198644',
 'bornstei': 'Q81279349',
 'boldt': 'Q120465',
 'blumenre': 'Q55674262',
 'arene': 'Q2633356',
 'adler': 'Q2058632',
 'gengenba': 'Q1305022',
 'rosenkra': 'Q4575420',
 'ovid': 'Q7198',
 'enking': 'Q1260554',
 'kernstoc': 'Q88076',
 'zurlinde': 'Q87705',
 'kotzeb-o': 'Q58828',
 'greyerzo': 'Q124718',
 'corvin': 'Q75265',
 'bismarck': 'Q8442',
 'weininge': 'Q78513',
 'sutermei': 'Q116096',
 'stoessl': 'Q2040715',
 'schwerio': 'Q1264679',
 'ruppius': 'Q2040358',
 'rung': 'Q6083705',
 'roquette': 'Q92500',
 'nordensk': 'Q440310',
 'ludwig': 'Q77321',
 'leixner': 'Q89699',
 'bierbaum': 'Q64001',
 'henne': 'Q4135503',
 'harnack': 'Q119170',
 'goldmann': 'Q64414863',
 'gildemei': 'Q73964',
 'flake': 'Q68109',
 'ernst': 'Q123291',
 'hartlebe': 'Q76279',
 'wildermt': 'Q69311',
 'krzyzano': 'Q2036789',
 'berndt': 'Q88061',
 'tiedeman': 'Q19222991',
 'spengler': 'Q57112',
 'levett': 'Q2036414',
 'boelcke': 'Q57716',
 'schubin': 'Q446713',
 'waechter': 'Q6248114',
 'woehrle': 'Q1393779',
 'wiener': 'Q22694619',
 'panizza': 'Q62871',
 'meding': 'Q2033865',
 'loerke': 'Q68110',
 'hoecker': 'Q78255',
 'wilde': 'Q30875',
 'levertin': 'Q668328',
 'schmitzo': 'Q126733',
 'chajjam': 'Q35900',
 'wohlbrue': 'Q2019750',
 'roelvaag': 'Q523105',
 'duun': 'Q721763',
 'baker': 'Q84761730',
 'okakura': 'Q942995',
 'mirbeau': 'Q23441',
 'novalis': 'Q60684',
 'jacques': 'Q75835',
 'hanried': 'Q1996827',
 'petersen': 'Q3877305',
 'lenclos': 'Q237045',
 'zinzendo': 'Q76336',
 'lenau': 'Q84280',
 'decius': 'Q65601',
 'gogol': 'Q43718',
 'ljesskow': 'Q209004',
 'manueln': 'Q670805',
 'bretonne': 'Q732729',
 'wiseman': 'Q672816',
 'machiave': 'Q1399',
 'eschstru': 'Q87140',
 'lambrech': 'Q1745845',
 'jokai': 'Q379621',
 'sadi': 'Q84413340',
 'multatul': 'Q154211',
 'nefzaui': 'Q2962111',
 'mendelss': 'Q76997',
 'strachwz': 'Q96416',
 'schwind': 'Q551901',
 'sophar': 'Q19220320',
 'schrebem': 'Q153160',
 'heimann': 'Q1667568',
 'hartmann': 'Q565133',
 'saphir': 'Q87685',
 'thuemmel': 'Q70443',
 'spector': 'Q1947402',
 'hunnius': 'Q89395',
 'moliere': 'Q687',
 'muhammad': 'Q9458',
 'cervante': 'Q5682',
 'montaign': 'Q41568',
 'revon': 'Q3310685',
 'arcybase': 'Q448143',
 'prischwi': 'Q700323',
 'lermonto': 'Q46599',
 'kusmin': 'Q460352',
 'bakunin': 'Q27645',
 'lindener': 'Q1928445',
 'kohlhaas': 'Q84413793',
 'conradmg': 'Q214306',
 'corvinmi': 'Q84761081',
 'mongdsi': 'Q188903',
 'sforim': 'Q359694',
 'lienert': 'Q121793',
 'schmidtm': 'Q95749',
 'maulbeck': 'Q84472948',
 'kern': 'Q1913993',
 'maximili': 'Q150726',
 'harden': 'Q63411',
 'bern': 'Q113939',
 'gorki': 'Q12706',
 'schenken': 'Q71616',
 'morold': 'Q94468',
 'wing': 'Q84415705',
 'wilke': 'Q84426982',
 'webermax': 'Q9387',
 'waldau': 'Q103953',
 'vogler': 'Q101909',
 'stirner': 'Q76725',
 'scheler': 'Q76521',
 'sauerlan': 'Q97409',
 'pulver': 'Q116515',
 'prels': 'Q61930459',
 'nordau': 'Q472270',
 'messer': 'Q65034967',
 'lieberma': 'Q158062',
 'kretzer': 'Q108847',
 'hofmannm': 'Q19513474',
 'herrmann': 'Q90810',
 'henning': 'Q1912673',
 'halbe': 'Q65042',
 'grad': 'Q18025500',
 'geissler': 'Q1912565',
 'fleische': 'Q81527439',
 'eyth': 'Q78267',
 'duerr': 'Q84412501',
 'dreysel': 'Q84761078',
 'dreyer': 'Q98705',
 'dauthend': 'Q481550',
 'burckhm': 'Q88819',
 'bruns': 'Q1912313',
 'barthel': 'Q85875',
 'bartels': 'Q19277705',
 'lindemay': 'Q43877',
 'renard': 'Q1399133',
 'maeterli': 'Q49747',
 'level': 'Q3301073',
 'leblanc': 'Q314993',
 'barres': 'Q314957',
 'merian': 'Q57968',
 'bodkin': 'Q6791578',
 'claudius': 'Q77338',
 'blank': 'Q19224541',
 'bandello': 'Q19054',
 'wesendon': 'Q63265',
 'shelley': 'Q47152',
 'opitz': 'Q60946',
 'montanus': 'Q1904590',
 'maurice': 'Q84761315',
 'luther': 'Q9554',
 'greif': 'Q1669190',
 'antonius': 'Q1430',
 'lafayett': 'Q237090',
 'olfers': 'Q1897556',
 'mancke': 'Q18025058',
 'ebnresch': 'Q93525',
 'sevigne': 'Q237103',
 'mariefra': 'Q5617',
 'zedelius': 'Q19224537',
 'sturza': 'Q19218968',
 'nathusiu': 'Q1897453',
 'gothein': 'Q97309',
 'lipsius': 'Q460534',
 'kernerma': 'Q15434626',
 'meinhard': 'Q1804481',
 'grazie': 'Q1484417',
 'bernhard': 'Q17578094',
 'ehrmann': 'Q1896790',
 'waser': 'Q1434539',
 'titelius': 'Q81300004',
 'mariathe': 'Q131706',
 'stona': 'Q523418',
 'leitner': 'Q1896079',
 'konopnic': 'Q257852',
 'janitsch': 'Q88216',
 'buol': 'Q15430840',
 'poradows': 'Q17425416',
 'audoux': 'Q466650',
 'sydow': 'Q1588192',
 'margvalo': 'Q220845',
 'navarra': 'Q190058',
 'georgy': 'Q1372193',
 'boehme': 'Q98639',
 'boie': 'Q1894950',
 'oliphant': 'Q2415217',
 'cicero': 'Q1541',
 'schwob': 'Q472697',
 'prevostm': 'Q326138',
 'proust': 'Q7199',
 'richthof': 'Q4701',
 'schneidm': 'Q84761119',
 'kyber': 'Q115335',
 'meysenbu': 'Q68795',
 'montgome': 'Q546949',
 'crusenst': 'Q204801',
 'hirschfe': 'Q57592',
 'lichtwer': 'Q177427',
 'thoresen': 'Q443649',
 'trott': 'Q1621969',
 'daudetle': 'Q92562',
 'lukian': 'Q177847',
 'westkirc': 'Q19218409',
 'reinhard': 'Q16739230',
 'muehlbac': 'Q76117',
 'hensel': 'Q91828',
 'glass': 'Q1230924',
 'ey': 'Q1876608',
 'ahlborn': 'Q1324050',
 'gottschl': 'Q65863',
 'coloma': 'Q4228309',
 'pirandel': 'Q1403',
 'winder': 'Q215606',
 'uhland': 'Q61058',
 'tieck': 'Q57239',
 'thoma': 'Q45309',
 'storch': 'Q1875077',
 'steub': 'Q1764269',
 'salomon': 'Q20758273',
 'rubiner': 'Q1874926',
 'richterl': 'Q551896',
 'rellstab': 'Q28858',
 'quidde': 'Q76696',
 'preller': 'Q215066',
 'nohl': 'Q97494',
 'kuelz': 'Q97797',
 'koehler': 'Q4251389',
 'jacobows': 'Q1874611',
 'ludwig2': 'Q44039',
 'ludwig1': 'Q44361',
 'hoelty': 'Q71456',
 'huna': 'Q23808394',
 'hevesi': 'Q86534',
 'habicht': 'Q5781244',
 'kosegart': 'Q71484',
 'ganghofe': 'Q77475',
 'fulda': 'Q72283',
 'friedlae': 'Q77627',
 'frahm': 'Q109146',
 'feuerbal': 'Q76422',
 'eichrodt': 'Q96692',
 'boerne': 'Q213595',
 'bechstei': 'Q66379',
 'aurbache': 'Q106617',
 'anzengru': 'Q93718',
 'holberg': 'Q216692',
 'ariosto': 'Q48900',
 'wienbarg': 'Q73929',
 'corinth': 'Q157610',
 'gall': 'Q105710',
 'francois': 'Q84820',
 'aston': 'Q67888',
 'anklam': 'Q84415684',
 'saint-si': 'Q463728',
 'weinert': 'Q103065',
 'spohr': 'Q57226',
 'lax': 'Q55902345',
 'couperus': 'Q437798',
 'salome': 'Q38873',
 'schmidtl': 'Q16471731',
 'daponte': 'Q268166',
 'vega': 'Q165257',
 'longus': 'Q314949',
 'liselott': 'Q57221',
 'braun': 'Q71372',
 'libai': 'Q7071',
 'carroll': 'Q38082',
 'wallace': 'Q357102',
 'tolstoi': 'Q7243',
 'tolstoil': 'Q1152362',
 'schueckg': 'Q78349',
 'sacher-m': 'Q78474',
 'ranke': 'Q77184',
 'weberleo': 'Q1587582',
 'schefer': 'Q62805',
 'loewenfe': 'Q1727246',
 'kompert': 'Q78940',
 'kolbe': 'Q1819722',
 'katscher': 'Q4217528',
 'hirschbe': 'Q1819686',
 'goecking': 'Q98454',
 'zell': 'Q19217463',
 'andrejew': 'Q310866',
 'trotzki': 'Q33391',
 'sternber': 'Q1818753',
 'leipzige': 'Q1818653',
 'greiner': 'Q1818576',
 'frobeniu': 'Q60570',
 'deutsch': 'Q2492405',
 'christ': 'Q77925',
 'lynch': 'Q50218665',
 'bruun': 'Q180097',
 'sterne': 'Q218960',
 'reissner': 'Q538379',
 'laotse': 'Q9333',
 'hearn': 'Q313638',
 'beeker': 'Q1795559',
 'schirmac': 'Q1651018',
 'kraftbue': 'Q81304934',
 'mikszath': 'Q350552',
 'tucholsk': 'Q57386',
 'martens': 'Q1793845',
 'kluge': 'Q215863',
 'geucke': 'Q80792009',
 'floerick': 'Q216746',
 'faber': 'Q1325871',
 'aram': 'Q1793352',
 'lasswitz': 'Q61453',
 'elster': 'Q550125',
 'holm': 'Q1378650',
 'balmont': 'Q314498',
 'kvwuerzb': 'Q77480',
 'telmann': 'Q98444',
 'konfuziu': 'Q4604',
 'heinroth': 'Q1745616',
 'groth': 'Q76494',
 'klabund': 'Q61263',
 'grahame': 'Q314897',
 'przerwa': 'Q473139',
 'kathari2': 'Q36450',
 'guendero': 'Q62053',
 'pierson': 'Q1459744',
 'perfallk': 'Q118145',
 'marinell': 'Q1733642',
 'holtei': 'Q66388',
 'contessa': 'Q96771',
 'masius': 'Q55065746',
 'wartenbu': 'Q19215162',
 'vorlaend': 'Q90180',
 'voll': 'Q18413222',
 'valentin': 'Q45255',
 'tanera': 'Q107494',
 'soehle': 'Q1733136',
 'storck': 'Q27733749',
 'stieler': 'Q73064',
 'spindler': 'Q87477',
 'simrock': 'Q70350',
 'ravendro': 'Q103704',
 'schoenhe': 'Q94707',
 'radek': 'Q84266',
 'moritz': 'Q215781',
 'paulik': 'Q19215119',
 'muellenh': 'Q67091',
 'may': 'Q22714',
 'marx': 'Q9061',
 'haeberli': 'Q1732209',
 'lerbs': 'Q1732148',
 'kraus': 'Q44328',
 'kautsky': 'Q76586',
 'immerman': 'Q213589',
 'hillebra': 'Q71106',
 'herloss': 'Q106889',
 'henckell': 'Q88710',
 'helfferi': 'Q67018',
 'langhein': 'Q95259',
 'ulrichs': 'Q60318',
 'strobl': 'Q84676',
 'gutzkow': 'Q76755',
 'gjelleru': 'Q131487',
 'nowak': 'Q7983614',
 'hensler': 'Q1731074',
 'wetzel': 'Q106711',
 'beckerkf': 'Q84523',
 'federn': 'Q94614',
 'ewald': 'Q1645523',
 'neumannk': 'Q84626',
 'franzos': 'Q78846',
 'broeger': 'Q124537',
 'heinrich': 'Q23666562',
 'bleibtre': 'Q95194',
 'heigel': 'Q86941',
 'varnhage': 'Q215691',
 'alberti': 'Q80794237',
 'adolph': 'Q1730220',
 'michaeli': 'Q265796',
 'capek': 'Q155855',
 'klosterma': 'Q84648',
 'wickram': 'Q73072',
 'eoetvoes': 'Q469996',
 'kraszews': 'Q254524',
 'svensson': 'Q983305',
 'moeser': 'Q65087',
 'kernerj': 'Q77280',
 'soyfer': 'Q45267',
 'vossjul': 'Q90626',
 'payer': 'Q223249',
 'wolff': 'Q215658',
 'zincgref': 'Q91923',
 'sturm': 'Q78269',
 'stinde': 'Q215090',
 'stettenh': 'Q98750',
 'steinber': 'Q84412465',
 'rodenber': 'Q85793',
 'haarhaus': 'Q1712899',
 'mosen': 'Q214737',
 'langbehn': 'Q68824',
 'koestlin': 'Q91932',
 'kreis': 'Q28070642',
 'hartj': 'Q76277',
 'hahnjul': 'Q81527604',
 'grosse': 'Q88970',
 'hitzig': 'Q70849',
 'lamettri': 'Q7068',
 'lespinas': 'Q450354',
 'dery': 'Q986949',
 'hirschju': 'Q84414167',
 'hawthorj': 'Q9016429',
 'gordonju': 'Q6306335',
 'goncourj': 'Q1234248',
 'verne': 'Q33977',
 'siber': 'Q1320219',
 'michelet': 'Q310791',
 'claretie': 'Q912271',
 'aurevill': 'Q314963',
 'aho': 'Q348623',
 'valera': 'Q463630',
 'queiroz': 'Q316327',
 'echegara': 'Q127349',
 'siebe': 'Q71947',
 'schneide': 'Q1670757',
 'schwerin': 'Q81283442',
 'lauff': 'Q85301',
 'hammerpu': 'Q89546',
 'eichndrf': 'Q77204',
 'scheffel': 'Q9082',
 'schreyvo': 'Q94645',
 'roth': 'Q78509',
 'richterj': 'Q1707885',
 'rankjo': 'Q1707864',
 'paquetj': 'Q84761057',
 'haegele': 'Q80795487',
 'goerres': 'Q215730',
 'bolanden': 'Q91180',
 'conrad': 'Q82925',
 'zedlitz': 'Q429184',
 'baierlei': 'Q1706560',
 'lux': 'Q1706538',
 'beringer': 'Q19214404',
 'wittmann': 'Q84412809',
 'treumann': 'Q1705907',
 'ruederer': 'Q1705581',
 'ponten': 'Q1481942',
 'messner': 'Q21039143',
 'kastein': 'Q71543',
 'hofmille': 'Q1704832',
 'hofbauer': 'Q23889105',
 'haltrich': 'Q327509',
 'gangl': 'Q1704635',
 'ettlinge': 'Q103571',
 'gleich': 'Q1704178',
 'swift': 'Q41166',
 'lie': 'Q469681',
 'mill': 'Q50020',
 'locke': 'Q9353',
 'ingram': 'Q972178',
 'keats': 'Q82083',
 'mackay': 'Q62258',
 'habberto': 'Q1700337',

### Just some book-keeping

In [ ]:
# OLD, already renamed. Also, badly chosen names.

fiction = fiction.rename(axis=1, mapper={'qid': 'author_qid', 'gbde_author_id' : 'pgde_author_id'})
fiction

,author,author_last,author_first,title,wd,gutenberg_id,year,url,pgde_author_id,author_qid
index,,,,,,,,,,
0,Arthur Achleitner,Achleitner,Arthur,Der Finanzer,NaN,NaN,1916,https://www.projekt-gutenberg.org/achleitn/fin...,achleitn,Q77439
1,Arthur Achleitner,Achleitner,Arthur,Das Schloß im Moor,NaN,NaN,1903,https://www.projekt-gutenberg.org/achleitn/moo...,achleitn,Q77439
2,Arthur Achleitner,Achleitner,Arthur,Familie Lugmüller,NaN,NaN,1896,https://www.projekt-gutenberg.org/achleitn/lug...,achleitn,Q77439
3,Arthur Achleitner,Achleitner,Arthur,Der Bezirkshauptmann. Erster Teil,NaN,NaN,1901,https://www.projekt-gutenberg.org/achleitn/bez...,achleitn,Q77439
4,Arthur Achleitner,Achleitner,Arthur,Geschichten aus den Bergen,NaN,NaN,1910,https://www.projekt-gutenberg.org/achleitn/ber...,achleitn,Q77439
...,...,...,...,...,...,...,...,...,...,...
4229,Arnold Zweig,Zweig,Arnold,Die Novellen um Claudia,NaN,52478,1912,NaN,NaN,NaN
4230,Friderike Maria Burger Winternitz Zweig,Zweig,Friderike Maria Burger Winternitz,Vögelchen,NaN,57114,1919,NaN,NaN,NaN
4231,Stefan Zweig,Zweig,Stefan,Amok,Q675609,57850,1922,https://www.projekt-gutenberg.org/zweig/amok/a...,zweig,Q78491
4232,Stefan Zweig,Zweig,Stefan,Brennendes Geheimnis: Erzählung,NaN,24173,1911,NaN,NaN,NaN
4233,Stefan Zweig,Zweig,Stefan,Die Liebe der Erika Ewald: Novellen,NaN,38686,1904,NaN,NaN,NaN

### Now we fill the new column with the newly fetched QIDs

In [46]:
fiction['author_qid'] = fiction['pgde_author_id'].map(author_dict)
fiction

,author,author_last,author_first,title,work_qid,gutenberg_id,year,url,pgde_author_id,author_qid,...,filename,author_gender,num_sents,num_tokens,source,work_qid_by,pgde_qid_by,pgus_qid_by,ed1_qid_by,1e_qid_by
index,,,,,,,,,,,,,,,,,,,,,
0,Arthur Achleitner,Achleitner,Arthur,Der Finanzer,NaN,NaN,1916,https://www.projekt-gutenberg.org/achleitn/fin...,achleitn,Q77439,...,Arthur_Achleitner_-_Der_Finanzer.txt,m,1723,24034,PG-DE,NaN,NaN,NaN,NaN,NaN
1,Arthur Achleitner,Achleitner,Arthur,Das Schloß im Moor,NaN,NaN,1903,https://www.projekt-gutenberg.org/achleitn/moo...,achleitn,Q77439,...,Arthur_Achleitner_-_Das_Schloß_im_Moor.txt,m,3460,51072,PG-DE,NaN,NaN,NaN,NaN,NaN
2,Arthur Achleitner,Achleitner,Arthur,Familie Lugmüller,NaN,NaN,1896,https://www.projekt-gutenberg.org/achleitn/lug...,achleitn,Q77439,...,Arthur_Achleitner_-_Familie_Lugmüller.txt,m,1967,26741,PG-DE,NaN,NaN,NaN,NaN,NaN
3,Arthur Achleitner,Achleitner,Arthur,Der Bezirkshauptmann. Erster Teil,NaN,NaN,1901,https://www.projekt-gutenberg.org/achleitn/bez...,achleitn,Q77439,...,Arthur_Achleitner_-_Der_Bezirkshauptmann._Erst...,m,2614,34895,PG-DE,NaN,NaN,NaN,NaN,NaN
4,Arthur Achleitner,Achleitner,Arthur,Geschichten aus den Bergen,NaN,NaN,1910,https://www.projekt-gutenberg.org/achleitn/ber...,achleitn,Q77439,...,Arthur_Achleitner_-_Geschichten_aus_den_Bergen...,m,6350,127192,PG-DE,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4229,Arnold Zweig,Zweig,Arnold,Die Novellen um Claudia,NaN,52478,1912,NaN,NaN,NaN,...,"Zweig,_Arnold_-_Die_Novellen_um_Claudia-52478.txt",m,2720,47335,PG-US,NaN,NaN,NaN,NaN,NaN
4230,Friderike Maria Burger Winternitz Zweig,Zweig,Friderike Maria Burger Winternitz,Vögelchen,NaN,57114,1919,NaN,NaN,NaN,...,"Zweig,_Friderike_Maria_Burger_Winternitz_-_Vög...",m,7846,104521,PG-US,NaN,NaN,NaN,NaN,NaN
4231,Stefan Zweig,Zweig,Stefan,Amok: Novellen einer Leidenschaft,Q675609,57850,1922,NaN,zweig,Q78491,...,"Zweig,_Stefan_-_Amok:_Novellen_einer_Leidensch...",m,3087,69716,PG-US,NaN,NaN,NaN,NaN,NaN
4232,Stefan Zweig,Zweig,Stefan,Brennendes Geheimnis: Erzählung,NaN,24173,1911,NaN,NaN,NaN,...,"Zweig,_Stefan_-_Brennendes_Geheimnis:_Erzählun...",m,1475,22509,PG-US,NaN,NaN,NaN,NaN,NaN
4233,Stefan Zweig,Zweig,Stefan,Die Liebe der Erika Ewald: Novellen,NaN,38686,1904,NaN,NaN,NaN,...,"Zweig,_Stefan_-_Die_Liebe_der_Erika_Ewald:_Nov...",m,2391,44067,PG-US,NaN,NaN,NaN,NaN,NaN

In [ ]:
fiction.to_csv(Path(collections_dir, 'de-fiction-pgde-auth-id.csv'))

#filename = 'de_fiction_metadata_2025-11-14T18.csv'
filename = f'de_fiction_metadata-{date_tag()}.csv'
logger.info(f'Writing file: {filename}')
fiction.to_csv(Path(collections_dir, filename))